### ISSUE TITLE
'sysinfo': a bytes-like object is required

### ISSUE THREAD

**Issue by LaZyDK** [BC-SECURITY/Empire#48]
## Empire Version
3.0 BC-Security Fork

## OS Information (Linux flavor, Python version)
Debian 10 Buster
Python 3.7.5
from Docker image: python:3.7.5-buster
Pulled: 2019-12-30

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I am able to interact with an agent to and successfully run "whoami" command. 
If I run "sysinfo" it fails with the error:
**[!] Error processing result packet from RHK1YSMF : a bytes-like object is required, not 'str'**

## Screenshot of error, embedded text output, or Pastebin link to the error
![Skærmbillede 2019-12-30 kl  13 51 01](https://user-images.githubusercontent.com/9623973/71582753-d700a600-2b0b-11ea-9bb8-3b0ef3f31b79.png)
![Skærmbillede 2019-12-30 kl  13 50 53](https://user-images.githubusercontent.com/9623973/71582786-ef70c080-2b0b-11ea-81d0-9d7bfd3a8ffc.png)

**Comment by Hubbl3** [comment]
@LaZyDK  we just merged over the 3.0-bug-fixes branch to the master branch which should have addressed this problem.

**Comment by Cx01N** [comment]
@LaZyDK It appears that you are running an older version. If you redownload as empire:latest, it should be version 3.0.1 and this will correct the issue. I just tested it and this error appears to be correct. Please let us know if you are still seeing something.

**Comment by LaZyDK** [comment]
@Cx01N 
It still does not work. Has the docker image been rebuild with the new bug fixes yet?

**Comment by LaZyDK** [comment]
I get the same error when I pull the v3.0.1 branch.

**Comment by Hubbl3** [comment]
@LaZyDK  I just pulled a docker image using `docker pull bcsecurity/empire:v3.0.1` and am unable to produce an error. Are you using a python or powershell agent?

**Comment by LaZyDK** [comment]
I am using the powershell agent as shown here. 
![Skærmbillede 2020-01-03 kl  09 11 45](https://user-images.githubusercontent.com/9623973/71713318-83db6b80-2e09-11ea-889c-ebdb7e4bb943.png)

Also I am using docker compose. I have tried both latest and 3.0.1, and both are freshly pulled. 
![Skærmbillede 2020-01-03 kl  09 14 37](https://user-images.githubusercontent.com/9623973/71713335-98b7ff00-2e09-11ea-9818-cb0769076832.png)

**Comment by vinnybod** [comment]
Hey, so I haven't had time to test this theory just yet, but I believe the issue here is related to the mounted volume.The giveaway is that we made some changes in 3.0.1 to the line endings on some of those print statements that don't appear in your screenshots.

If you run `empire:latest` or `empire:v3.0.1` without the mounted volumes, my theory is that the sysinfo bug will go away. If that is the case, then we will just need to rethink the persistent storage a bit.

**Comment by vinnybod** [comment]
@LaZyDK I tested my theory and this is the case for me. I would recommend using different volumes for different versions of empire for the time being.
