### ISSUE TITLE
[BUG] FileNotFoundError when Obfuscate stager windows/launcher_bat

### ISSUE THREAD

**Issue by DerKiLLa** [BC-SECURITY/Empire#522]
## Empire Version
- Empire 4.2.0 (Kali Edition)

## OS Information (Linux flavor, Python version)
- OS: Kali
- Python: 3.9.8

## Describe the bug
When i create a stager, i can't use the "Obfuscate"-Option. Neither in Starkiller, nor in the bash-client.

`FileNotFoundError(2, 'No such file or directory')`

## To Reproduce
usestager windows/launcher_bat
set Listener http
set Obfuscate True
execute

## Expected behavior
An obfuscated launcher.bat File

**Comment by DerKiLLa** [comment]
Anything about this?

**Comment by Cx01N** [comment]
@DerKiLLa there was a bug in obfuscation in 4.2 that we fixed in 4.3. It looks like it's working for me, but can you give that a try in kali and see if it fixes your issue?

**Comment by shellshoc-holmes** [comment]
Hey, just ran into the same problem as DerKilla. Kali is updated, purged the empire installation and reinstalled it but the problem persists in freshly installed 4.3.

**Comment by DerKiLLa** [comment]
Same for me ... updated kali and still error "_Error: FileNotFoundError(2, 'No such file or directory')_"

**[Version] 4.3.0 BC Security Fork**

**Comment by Cx01N** [comment]
Found an issue with the Kali installer. Thanks for checking and letting us know. It wasn't pulling the proper file during the setup process. There will be a 4.3.2 coming out that should fix this. But until then, if you clone the Empire GitHub repo and run 'sudo ./setup/install.sh'. It should load the files properly for the kali version. For some reason, Invoke-Obfuscation isn't being imported into the correct directory.
